# Architecture
arch: MSNet

# ===== Dataset ===== #
set: Caltech256
num_classes: 10
mix_up: 0.8
cutmix: 1.0
auto_augment: rand-m9-mstd0.5-inc1
interpolation: bicubic
mixup_prob: 1.
switch_prob: 0.5
mixup_mode: batch
crop: True
re_prob: 0.25
re_mode: pixel
re_count: 1
val_split: True
test_name: "test"

# ===== Learning Rate Policy ======== #
optimizer: momentum
base_lr: 0.01
warmup_lr: 0.000007
min_lr: 0.00005
lr_scheduler: cosine_lr
warmup_length: 10

# ===== Network training config ===== #
amp_level: O1
keep_bn_fp32: True
beta: [ 0.9, 0.999 ]
clip_global_norm_value: 1.
is_dynamic_loss_scale: True
epochs: 100
label_smoothing: 0.1
weight_decay: 0.0004
momentum: 0.9
batch_size: 32

# ===== Hardware setup ===== #
num_parallel_workers: 16
device_target: Ascend
device_num: 1
graph_mode: 0

# ===== Model config ===== #
drop_path_rate: 0.5
drop_rate: 0.0
image_size: 224